import Head from 'next/head'
import EmpleadosList from '../src/components/EmpleadosList'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Prueba Qenta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EmpleadosList />
      </main>
    </div>
  )
}
